Update the gitignore file. Add a job to my pipeline that syncs files from this local dev environment to a dev aws s3 bucket.

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -3,7 +3,7 @@ include:
   - template: Security/Secret-Detection.gitlab-ci.yml
 
 variables:
-  SECRET_DETECTION_ENABLED: 'true'
+  SECRET_DETECTION_ENABLED: "true"
   GIT_DEPTH: 0
 
 stages:
@@ -12,7 +12,6 @@ stages:
   - test
   - build
   - deploy
-
 
 github:
   stage: ci
@@ -33,3 +32,28 @@ github:
   rules:
     - if: '$CI_COMMIT_BRANCH == "main"'
       when: always
+
+deploy_to_dev_environment:
+  image: python:3.12
+  stage: deploy
+  script:
+    - set -e
+    - echo "Installing AWS CLI..."
+    - pip install --upgrade awscli
+    - echo "Checking out code..."
+    - echo "Configuring AWS credentials..."
+    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
+    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
+    - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
+    - echo "Syncing files to AWS S3 bucket..."
+    - aws s3 sync /Users/mike/Desktop/Dev/Web/cloudops-status-page/services/michael-burbank/ s3://$S3_BUCKET_NAME --exclude "*" --include "services/michael-burbank/frontend/**"
+    - |
+      echo "Website URL: http://${S3_BUCKET_NAME}.s3-website-${AWS_DEFAULT_REGION}.amazonaws.com"
+      echo "Invalidating CloudFront Distribution..."
+    - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
+    - echo "Deployed to development environment."
+  environment:
+    name: development
+    url: https://dev.example.com
+  only:
+    - main
